const nodemailer = require("nodemailer");
const logger = require("./logger");

const sendEmail = (mailBody) => {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.userEmail,
      pass: process.env.userPassword,
    },
  });

  const mailOptions = mailBody;
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      logger.error(error);
    } else {
      logger.log(`Email sent: ${info.response}`);
    }
  });
};

const sendResetTokenEmail = (userDetails) => {
  const mailBody = {
    from: process.env.EmailFrom,
    to: userDetails.email,
    subject: "Reset password token generated - ToDo App",
    html: `
    <div style="width: 88%; height: 88%; margin: auto; text-align: left">
    <p style="font-size: larger; font-family: 'Franklin Gothic Medium'">
      <b> Dear ${userDetails.name},</b>
    </p>
    <h3 style="font-family: 'Franklin Gothic Medium'; padding: 10px">
      An auth token to reset password has been generated successfully!
    </h3>
    <p
      style="
        font-size: large;
        font-family: 'Franklin Gothic Medium';
        padding: 10px;
      "
    >
      The auth token is valid for 30 minutes from the time its generated. 
      Enter this token while you try to reset your password.
    </p>
    <p
      style="
        font-family: 'Franklin Gothic Medium';
        font-size: larger;
        padding: 10px;
      "
    >     
      Your generated token is :<b> ${userDetails.resetToken}</b>
    </p>
    <p
      style="
        padding: 10px;
        font-size: larger;
        font-family: 'Franklin Gothic Medium';
      "
    >
      Please Save this email for future reference. If you have questions,
      please contact the support team.
      <br />This email is auto generated by software, do not reply back to
      this email.
      <br />
      <br />
      <b>Thank You,</b><br />
      ToDo App Support
    </p>
  </div>`,
  };
  sendEmail(mailBody);
};

module.exports = {
  sendResetTokenEmail,
};
