export const SET_LOADER = "SET_LOADER";
export const UNSET_LOADER = "UNSET_LOADER";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

// Auth action types
export const SAVE_AUTH_TOKEN = "SAVE_AUTH_TOKEN";
export const REMOVE_AUTH_TOKEN = "REMOVE_AUTH_TOKEN";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

export const UPDATE_CATEGORY_LIST = "UPDATE_CATEGORY_LIST";
export const UPDATE_TASK_LIST = "UPDATE_TASK_LIST";
